classDiagram

DeploymentItem

ReleaseStream

Pipeline

DeploymentWindow

Journey

User

DeploymentItem --> User

DeploymentItem --> Journey

DeploymentItem --> ReleaseStream

ReleaseStream --> DeploymentWindow