flowchart LR

DashboardModule

ReleaseModule

DeploymentModule

PipelineModule

WindowModule

GitModule

DecisionEngine

Notification

DeploymentModule --> DecisionEngine

ReleaseModule --> DecisionEngine

DecisionEngine --> Notification