flowchart LR

Developer

QA

ReleaseManager

GitLab

ReleaseFlowPlatform

Developer --> ReleaseFlowPlatform

QA --> ReleaseFlowPlatform

ReleaseManager --> ReleaseFlowPlatform

GitLab --> ReleaseFlowPlatform